require(gWidgets)
options("guiToolkit"="RGtk2")
widget.env <- function()
  {
    view <- vector('list',1)
    base <- gwindow('cepp Engine',visible=TRUE)
    spawn.ggobi <- gbutton("Spawn GGobi",container=base)
    choose.set <- gbutton("Choose Data Set",container=base)

  }
obj <- gbutton("Hello World!",container=gwindow())
obj <- glabel("Hello world", container = gwindow())
obj <- gedit("Hello world", container = gwindow())
obj <- gtext("Hello world", container = gwindow())
obj <- gradio(c("hello","world"), container=gwindow())
obj <- gcombobox(c("hello","world"), container=gwindow())
obj <- gcombobox(c("hello","world"), editable=TRUE, container=gwindow())
obj <- gtable(c("hello","world"), container=gwindow())
obj <- gcheckboxgroup(c("hello","world"), container=gwindow())
obj <- gslider(from=0, to = 7734, by =100, value=0,container=gwindow())
obj <- gspinbutton(from=0, to = 7734, by =100, value=0,container=gwindow())
###
win <- gwindow("Hello World, ad nauseum", visible=TRUE)
group <- gframe(horizontal = FALSE, container=win)
obj <- gbutton("Hello...",container=group,handler = function(h,...) gmessage("world"))
obj <- glabel("Hello...", container =group,handler = function(h,...) gmessage("world"))
obj <- gcombobox(c("Hello","world"), container=group)
obj <- gedit("Hello world", container=group)
obj <- gtext("Hello world", container=group, font.attr=list(style="bold"))
###
win <- gwindow("cepp Engine", visible=TRUE)
group0 <- ggroup(horizontal = FALSE, container=win)
nb <- gnotebook(container = group0, expand=TRUE)
group.nb <- ggroup(horizontal = FALSE, container=nb,label="Page 1")
obj <- gradio(c("hello","world"), container=nb)
obj <- gcheckboxgroup(c("hello","world"), container=gwindow())
group.nb.1 <- ggroup(horizontal = TRUE, container=group.nb)
glabel("Move ", container = group.nb.1)
obj2 <- gcombobox(c("Brush","Glyph"),container = group.nb.1)
glabel("group ",container = group.nb.1)
obj2 <- gcombobox(1:10, container=group.nb.1)
glabel("to ", container =group.nb.1)
obj4 <- gcombobox(c('Fixed Set ','Target Set ','Unfixed Set (Release)'), container=group.nb.1)
glabel("Information", container =group.nb)
obj5 <- gtext("This current view has moved points",container=group.nb)
obj6 <- gbutton("Refresh Information",container=group.nb,handler = function(h,...) gmessage("world"))
glabel("Selection Information",container=group0)
obj7 <- gtable(dd,container=group0,expand=TRUE)
